name: PR Check

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip-pr-checks') }}
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      yarn-cache-dir-path: ${{ steps.yarn-cache-dir-path.outputs.out }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "16.x"
      - uses: ./.github/local-actions/yarn-install-and-cache

  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    needs:
      - prepare
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "16.x"
      - uses: ./.github/local-actions/yarn-install-and-cache
      - name: Create .env file
        shell: bash
        run: |
          echo -n "" > .env
          echo DATA_SPREADSHEET_ID=${{ secrets.DATA_SPREADSHEET_ID }} >> .env
          echo GOOGLE_PRIVATE_KEY="\"${{ secrets.GOOGLE_PRIVATE_KEY }}\"" >> .env
          echo GOOGLE_SERVICE_ACCOUNT_EMAIL=${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }} >> .env
      - name: Spellcheck
        shell: bash
        run: |
          yarn spellcheck

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs:
      - prepare
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "16.x"
      - uses: ./.github/local-actions/yarn-install-and-cache
      - name: Lint
        shell: bash
        run: |
          yarn lint-ci

  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - prepare
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "16.x"
      - uses: ./.github/local-actions/yarn-install-and-cache
      - name: Test
        shell: bash
        run: |
          yarn test-ci
